### ISSUE TITLE
Reported test run durations are affected by freezegun

### ISSUE THREAD

**Issue by gricey432** [buildkite/test-collector-python#27]
Just tried this out for the first time and the reported runtimes for my suite as well as some of the tests are wildly wrong.

The suite ran in about 15 minutes.

![2024-04-16_11-20-54](https://github.com/buildkite/test-collector-python/assets/1611345/903533f4-5b0f-4497-9756-fa5ee4b8db95)

The tests which have the huge runtimes are all using Freezegun to mess with the clock https://github.com/spulec/freezegun which feels like it's probably related.

Freezegun has its own ignore system, unsure if that's the best fix for this or if the test collector should automatically handle libraries like this.

**Comment by gricey432** [comment]
I've confirmed it's definitely an interaction with freezegun. Adding the following to conftest resolved it.

```python
import freezegun

freezegun.configure(extend_ignore_list=['buildkite_test_collector'])
```

**Comment by joshprice** [comment]
Thanks for raising this, don't think we can reasonably support such behaviour automatically for all time mocking tools.

Going to close this issue based on the fact that the ignore list fix works around it.

See https://github.com/spulec/freezegun?tab=readme-ov-file#ignore-packages for more details.
