### ISSUE TITLE
Cannot supply message from github actions CI

### ISSUE THREAD

**Issue by petemounce** [buildkite/test-collector-python#31]
https://github.com/buildkite/test-collector-python/blob/main/src/buildkite_test_collector/collector/run_env.py#L57 hard-codes `message=None` when the collector detects it's running inside github actions.

It's pretty easy to offer the commit message to the collector; `export GITHUB_MESSAGE="$(git log -1 --pretty=%B | head -1)" and that's what I tried - then I tried `BUILDKITE_ANALYTICS_MESSAGE` and `BUILDKITE_MESSAGE` before ending up reading the code :)

Would you welcome a PR that allows the `=None` parameters to be overridden by env-vars?

Even if I'm forced to use github actions, I'd love to use all the features of test analytics.

**Comment by jimsynz** [comment]
Hi there. I'd for sure welcome a PR that changes this.

**Comment by petemounce** [comment]
@jimsynz #32 is ready for your reviewing pleasure :)

(Please let me know what kind of coverage you might like; I kinda figured `__get_env` was already covered, but am totally open to adding things as you direct)

**Comment by petemounce** [comment]
@jimsynz thanks for the merge! Do you have an ETA for a release that this will appear in?

**Comment by jimsynz** [comment]
@gchan any chance you can cut a release?

**Comment by gchan** [comment]
I've published v0.1.9 of the collector with your update @petemounce. Thanks for your contribution and please let us know if you find any issues with this build!

cc @jimsynz
