### ISSUE TITLE
typing.Literal requires python 3.8

### ISSUE THREAD

**Issue by tigris** [buildkite/test-collector-python#5]
It seems some code [here](https://github.com/buildkite/test-collector-python/blob/b1d17bb96730d13bfb477725e750b6dc3db919a3/src/buildkite_test_collector/collector/payload.py#L4) is relying on `typing.Literal`.

However, according to python [docs](https://docs.python.org/3.8/library/typing.html#typing.Literal), this type was only introduced in python `3.8`, making this library unusable on python `3.7`.

I don't see anything in the `README.md` specifying a minimum python version, nor does the `setup.py` use the `python_requires` to specify one. I'm unsure if the team have decided on a minimum version or not. Python 3.7 is officially supported until 27 Jun 2023, which is not that far away, so perhaps customers should just upgrade to 3.8. Still be good to document this somewhere.

**Comment by jasmine-q** [comment]
Hi @tigris, thanks for your feedback.
I'm on the Test Analytics team but I am unfortunately not too familiar with python, so I would really appreciate if you could review my PR https://github.com/buildkite/test-collector-python/pull/6

**Comment by jasmine-q** [comment]
New release resolves the issue https://github.com/buildkite/test-collector-python/releases/tag/v0.1.2
