### ISSUE TITLE
Debugging not honoured

### ISSUE THREAD

**Issue by tigris** [buildkite/test-collector-python#7]
Setting `BUILDKITE_ANALYTICS_DEBUG_ENABLED=true` seems to have no impact for this collector. It'd be nice to be able to turn it on to verify what is (or in my case wasn't) working.

(FWIW- my scenario was a typo in the ENV var for the token, so the collector didn't upload anything, and debug wasn't able to help me determine that due to [this guard clause](https://github.com/buildkite/test-collector-python/blob/main/src/buildkite_test_collector/collector/api.py#L14)).

**Comment by jimsynz** [comment]
Hi @tigris. Thanks for the report.

You're right that there isn't any debug output present in this collector.  It seems sensible to me that at least if `BUILDKITE_ANALYTICS_DEBUG_ENABLED` is present and `BUILDKITE_ANALYTICS_TOKEN` is not it should emit a warning.   I'll get on that.
